// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetaDataBase.proto

package protocol;

public final class MetaDataBase {
  private MetaDataBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MetaDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.MetaData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sys = 1;</code>
     * @return The sys.
     */
    java.lang.String getSys();
    /**
     * <code>string sys = 1;</code>
     * @return The bytes for sys.
     */
    com.google.protobuf.ByteString
        getSysBytes();

    /**
     * <code>string module = 2;</code>
     * @return The module.
     */
    java.lang.String getModule();
    /**
     * <code>string module = 2;</code>
     * @return The bytes for module.
     */
    com.google.protobuf.ByteString
        getModuleBytes();

    /**
     * <code>string direct = 3;</code>
     * @return The direct.
     */
    java.lang.String getDirect();
    /**
     * <code>string direct = 3;</code>
     * @return The bytes for direct.
     */
    com.google.protobuf.ByteString
        getDirectBytes();

    /**
     * <code>string gToken = 4;</code>
     * @return The gToken.
     */
    java.lang.String getGToken();
    /**
     * <code>string gToken = 4;</code>
     * @return The bytes for gToken.
     */
    com.google.protobuf.ByteString
        getGTokenBytes();

    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code protocol.MetaData}
   */
  public static final class MetaData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.MetaData)
      MetaDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MetaData.newBuilder() to construct.
    private MetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetaData() {
      sys_ = "";
      module_ = "";
      direct_ = "";
      gToken_ = "";
      data_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MetaData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MetaData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sys_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              module_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              direct_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              gToken_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.MetaDataBase.internal_static_protocol_MetaData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.MetaDataBase.internal_static_protocol_MetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.MetaDataBase.MetaData.class, protocol.MetaDataBase.MetaData.Builder.class);
    }

    public static final int SYS_FIELD_NUMBER = 1;
    private volatile java.lang.Object sys_;
    /**
     * <code>string sys = 1;</code>
     * @return The sys.
     */
    @java.lang.Override
    public java.lang.String getSys() {
      java.lang.Object ref = sys_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sys_ = s;
        return s;
      }
    }
    /**
     * <code>string sys = 1;</code>
     * @return The bytes for sys.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSysBytes() {
      java.lang.Object ref = sys_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sys_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODULE_FIELD_NUMBER = 2;
    private volatile java.lang.Object module_;
    /**
     * <code>string module = 2;</code>
     * @return The module.
     */
    @java.lang.Override
    public java.lang.String getModule() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        module_ = s;
        return s;
      }
    }
    /**
     * <code>string module = 2;</code>
     * @return The bytes for module.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModuleBytes() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECT_FIELD_NUMBER = 3;
    private volatile java.lang.Object direct_;
    /**
     * <code>string direct = 3;</code>
     * @return The direct.
     */
    @java.lang.Override
    public java.lang.String getDirect() {
      java.lang.Object ref = direct_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direct_ = s;
        return s;
      }
    }
    /**
     * <code>string direct = 3;</code>
     * @return The bytes for direct.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDirectBytes() {
      java.lang.Object ref = direct_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direct_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GTOKEN_FIELD_NUMBER = 4;
    private volatile java.lang.Object gToken_;
    /**
     * <code>string gToken = 4;</code>
     * @return The gToken.
     */
    @java.lang.Override
    public java.lang.String getGToken() {
      java.lang.Object ref = gToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gToken_ = s;
        return s;
      }
    }
    /**
     * <code>string gToken = 4;</code>
     * @return The bytes for gToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGTokenBytes() {
      java.lang.Object ref = gToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSysBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sys_);
      }
      if (!getModuleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, module_);
      }
      if (!getDirectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, direct_);
      }
      if (!getGTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gToken_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSysBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sys_);
      }
      if (!getModuleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, module_);
      }
      if (!getDirectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, direct_);
      }
      if (!getGTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gToken_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.MetaDataBase.MetaData)) {
        return super.equals(obj);
      }
      protocol.MetaDataBase.MetaData other = (protocol.MetaDataBase.MetaData) obj;

      if (!getSys()
          .equals(other.getSys())) return false;
      if (!getModule()
          .equals(other.getModule())) return false;
      if (!getDirect()
          .equals(other.getDirect())) return false;
      if (!getGToken()
          .equals(other.getGToken())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SYS_FIELD_NUMBER;
      hash = (53 * hash) + getSys().hashCode();
      hash = (37 * hash) + MODULE_FIELD_NUMBER;
      hash = (53 * hash) + getModule().hashCode();
      hash = (37 * hash) + DIRECT_FIELD_NUMBER;
      hash = (53 * hash) + getDirect().hashCode();
      hash = (37 * hash) + GTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getGToken().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.MetaDataBase.MetaData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MetaDataBase.MetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.MetaDataBase.MetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MetaDataBase.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.MetaDataBase.MetaData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.MetaData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.MetaData)
        protocol.MetaDataBase.MetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.MetaDataBase.internal_static_protocol_MetaData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.MetaDataBase.internal_static_protocol_MetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.MetaDataBase.MetaData.class, protocol.MetaDataBase.MetaData.Builder.class);
      }

      // Construct using protocol.MetaDataBase.MetaData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sys_ = "";

        module_ = "";

        direct_ = "";

        gToken_ = "";

        data_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.MetaDataBase.internal_static_protocol_MetaData_descriptor;
      }

      @java.lang.Override
      public protocol.MetaDataBase.MetaData getDefaultInstanceForType() {
        return protocol.MetaDataBase.MetaData.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.MetaDataBase.MetaData build() {
        protocol.MetaDataBase.MetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.MetaDataBase.MetaData buildPartial() {
        protocol.MetaDataBase.MetaData result = new protocol.MetaDataBase.MetaData(this);
        result.sys_ = sys_;
        result.module_ = module_;
        result.direct_ = direct_;
        result.gToken_ = gToken_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.MetaDataBase.MetaData) {
          return mergeFrom((protocol.MetaDataBase.MetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.MetaDataBase.MetaData other) {
        if (other == protocol.MetaDataBase.MetaData.getDefaultInstance()) return this;
        if (!other.getSys().isEmpty()) {
          sys_ = other.sys_;
          onChanged();
        }
        if (!other.getModule().isEmpty()) {
          module_ = other.module_;
          onChanged();
        }
        if (!other.getDirect().isEmpty()) {
          direct_ = other.direct_;
          onChanged();
        }
        if (!other.getGToken().isEmpty()) {
          gToken_ = other.gToken_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.MetaDataBase.MetaData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.MetaDataBase.MetaData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sys_ = "";
      /**
       * <code>string sys = 1;</code>
       * @return The sys.
       */
      public java.lang.String getSys() {
        java.lang.Object ref = sys_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sys_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sys = 1;</code>
       * @return The bytes for sys.
       */
      public com.google.protobuf.ByteString
          getSysBytes() {
        java.lang.Object ref = sys_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sys_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sys = 1;</code>
       * @param value The sys to set.
       * @return This builder for chaining.
       */
      public Builder setSys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sys_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sys = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSys() {
        
        sys_ = getDefaultInstance().getSys();
        onChanged();
        return this;
      }
      /**
       * <code>string sys = 1;</code>
       * @param value The bytes for sys to set.
       * @return This builder for chaining.
       */
      public Builder setSysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sys_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object module_ = "";
      /**
       * <code>string module = 2;</code>
       * @return The module.
       */
      public java.lang.String getModule() {
        java.lang.Object ref = module_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          module_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string module = 2;</code>
       * @return The bytes for module.
       */
      public com.google.protobuf.ByteString
          getModuleBytes() {
        java.lang.Object ref = module_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          module_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string module = 2;</code>
       * @param value The module to set.
       * @return This builder for chaining.
       */
      public Builder setModule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string module = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearModule() {
        
        module_ = getDefaultInstance().getModule();
        onChanged();
        return this;
      }
      /**
       * <code>string module = 2;</code>
       * @param value The bytes for module to set.
       * @return This builder for chaining.
       */
      public Builder setModuleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        module_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object direct_ = "";
      /**
       * <code>string direct = 3;</code>
       * @return The direct.
       */
      public java.lang.String getDirect() {
        java.lang.Object ref = direct_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direct_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direct = 3;</code>
       * @return The bytes for direct.
       */
      public com.google.protobuf.ByteString
          getDirectBytes() {
        java.lang.Object ref = direct_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direct_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direct = 3;</code>
       * @param value The direct to set.
       * @return This builder for chaining.
       */
      public Builder setDirect(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string direct = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirect() {
        
        direct_ = getDefaultInstance().getDirect();
        onChanged();
        return this;
      }
      /**
       * <code>string direct = 3;</code>
       * @param value The bytes for direct to set.
       * @return This builder for chaining.
       */
      public Builder setDirectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direct_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gToken_ = "";
      /**
       * <code>string gToken = 4;</code>
       * @return The gToken.
       */
      public java.lang.String getGToken() {
        java.lang.Object ref = gToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gToken = 4;</code>
       * @return The bytes for gToken.
       */
      public com.google.protobuf.ByteString
          getGTokenBytes() {
        java.lang.Object ref = gToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gToken = 4;</code>
       * @param value The gToken to set.
       * @return This builder for chaining.
       */
      public Builder setGToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gToken = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGToken() {
        
        gToken_ = getDefaultInstance().getGToken();
        onChanged();
        return this;
      }
      /**
       * <code>string gToken = 4;</code>
       * @param value The bytes for gToken to set.
       * @return This builder for chaining.
       */
      public Builder setGTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 5;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.MetaData)
    }

    // @@protoc_insertion_point(class_scope:protocol.MetaData)
    private static final protocol.MetaDataBase.MetaData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.MetaDataBase.MetaData();
    }

    public static protocol.MetaDataBase.MetaData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MetaData>
        PARSER = new com.google.protobuf.AbstractParser<MetaData>() {
      @java.lang.Override
      public MetaData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MetaData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetaData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetaData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.MetaDataBase.MetaData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_MetaData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_MetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MetaDataBase.proto\022\010protocol\"U\n\010MetaDa" +
      "ta\022\013\n\003sys\030\001 \001(\t\022\016\n\006module\030\002 \001(\t\022\016\n\006direc" +
      "t\030\003 \001(\t\022\016\n\006gToken\030\004 \001(\t\022\014\n\004data\030\005 \001(\tB\030\n" +
      "\010protocolB\014MetaDataBaseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_MetaData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_MetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_MetaData_descriptor,
        new java.lang.String[] { "Sys", "Module", "Direct", "GToken", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
